### ISSUE TITLE
Question about vicuna version

### ISSUE THREAD

**Issue by CleyLyChen** [YuanGongND/ltu#28]
Hi, great work!
I have a small question that what version of vicuna you used in ltu and ltu-as?
Thanks.

**Comment by YuanGongND** [comment]
hi there,

It should be v1.1 https://huggingface.co/lmsys/vicuna-7b-v1.1/tree/main. 

This work is mostly finished in April 2023, when 1.1 is the latest version. You can check the hash to confirm this. 

-Yuan
