### ISSUE TITLE
Eval_metrics

### ISSUE THREAD

**Issue by joemzhao** [YuanGongND/ltu#29]
Hi Yuan, thanks a lot for the nice work.

It seems the evaluation scripts for computing cider/spice scores are missing. For example:
"""
from eval_metrics import evaluate_metrics 
"""
(https://github.com/YuanGongND/ltu/blob/main/src/ltu/eval/eval_audiocaps.py#L14)

could you share about this? Thank you very much

**Comment by YuanGongND** [comment]
hi there,

Thanks for pointing this out. 

The script depends on this package: https://github.com/audio-captioning/caption-evaluation-tools (not our work, but metrics script used by DCASE).

We share our script just to show how we postprocess the prediction. The evaluation part is standard.

-Yuan

**Comment by joemzhao** [comment]
Understood -- thanks for the help!

**Comment by YuanGongND** [comment]
Let me know if there's any problem running the script. I think you should be able to run it if you put our script in the same dir of that package.

-Yuan

**Comment by joemzhao** [comment]
Hi Yuan -- thanks for the kind help! Yes, I can run the scripts to obtain the scores properly.
