### ISSUE TITLE
Question: About the OpenAQA dataset.

### ISSUE THREAD

**Issue by wangwen-banban** [YuanGongND/ltu#48]
Great work! I meet some problem about the dataset.
I’m trying to retrieve Q-A pairs that do not have answers(6%). I used the phrase ‘it cannot be determined’ to search for the data, but I only found 1k pairs. Do you have a better method to retrieve all of such data? I would really appreciate it

**Comment by YuanGongND** [comment]
yes I do have a longer list for the keywords. 

Can you check this? https://github.com/YuanGongND/ltu/blob/main/openasqa/utils/filter_not_answerable_qa.py 

I also think in the breakdown dataset we have no-notanswerable question and include-notanswerable question version. 

-Yuan

**Comment by wangwen-banban** [comment]
thanks
